export default ['🎮 Gaming',
    '🎵 Music',
    '📖 Book',
    '💪 Gym',
    '👚 Fashion',
    '📱 Technology',
    '✈️ Travel',
    '🎨 Arts',
    '🌳 Nature',
    '💰 Finance',
    '🚘 Cars',
    '🐶 Animal',
    '🚴 Sports',
    '🏕️ Outdoors',
    '🍜 Foodie',
    '💼 Business',
    '🍷 Wine',
    '🎞️ Movies']